apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{ template "typesense.fullname" . }}
  labels: {{- include "typesense.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "typesense.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  serviceName: {{ template "typesense.fullname" . }}
  template:
    metadata:
      labels: {{- include "typesense.labels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "topology.kubernetes.io/zone"
                  operator: In
                  values:
                    - eu-west-1c
      volumes:
        - name: config-nodes
          configMap:
            name: {{ template "typesense.fullname" . }}
            items:
              - key: nodes
                path: nodes
      containers:
        - name: typesense
          image: {{ template "typesense.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: TYPESENSE_DATA_DIR
              value: {{ .Values.persistence.path }}
            - name: TYPESENSE_API_KEY
              value: {{ .Values.apiKey }}
          ports:
            - name: http
              containerPort: {{ .Values.applicationPort }}
            - name: peering
              containerPort: {{ .Values.peeringPort }}
          args:
            - --data-dir
            - /data
            - --api-key
            - {{ .Values.apiKey }}
            - --listen-port
            - "{{ .Values.applicationPort }}"
            - --nodes
            - /etc/typesense/nodes/nodes
          livenessProbe:
              httpGet:
                path: /health
                port: http
              initialDelaySeconds: 120 
              timeoutSeconds: 5
              failureThreshold: 6
          volumeMounts:
            - name: data  
              mountPath: {{ .Values.persistence.path }}
            - name: config-nodes
              mountPath: /etc/typesense/nodes
  volumeClaimTemplates:  
    - metadata:
        name: data  
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 25Gi  
